server:
  port: 3344

spring:
  application:
    name: config-centor
  cloud:
    config:
      server:
        git:
          uri: https://github.com/RuiCoo/config-center.git
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7001/eureka