server:
  port: 9001

spring:
  application:
    name: hystrix-consumer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
    fetch-registry: true
    register-with-eureka: true

ribbon:
  ReadTimeout: 4000